pub struct VulkanResidentModelPackage {
    pub package_id: String,
    pub device_id: String,
    pub dynamic_state_capacity_activations: usize,
    pub permanent_parameter_count: usize,
    pub permanent_parameter_bytes: usize,
    pub transducer_parameter_count: usize,
    pub transducer_parameter_bytes: usize,
    pub reusable_kernel_word_count: usize,
    placed_plan: VulkanPlacedStreamCircuitPlan,
    mounted_bound: VulkanMountedPlacedBoundDispatchPlan,
    loaded_manifest: VulkanLoadedReusableKernelArtifactManifest,
    parameter_buffers: Arc<VulkanPermanentParameterBuffers>,
    transducer_parameter_buffers: Arc<VulkanPermanentParameterBuffers>,
    input_transducer_spirv_words: Vec<u32>,
    embedding_norm_spirv_words: Vec<u32>,
    tied_projection_spirv_words: Vec<u32>,
    sampler_kernels: Vec<VulkanResidentSamplerKernelArtifact>,
    input_transducer_spec: VulkanResidentInputEmbeddingTransducerSpec,
    output_transducer_spec: VulkanResidentOutputTransducerSpec,
    sampler_spec: VulkanResidentSamplerSpec,
}

pub struct VulkanResidentModelPackageDeviceSlice {
    pub package_id: String,
    pub device_id: String,
    pub dynamic_state_capacity_activations: usize,
    pub hosted_component_count: usize,
    pub incoming_edge_count: usize,
    pub outgoing_edge_count: usize,
    pub permanent_parameter_count: usize,
    pub permanent_parameter_bytes: usize,
    pub reusable_kernel_word_count: usize,
    placed_plan: VulkanPlacedStreamCircuitPlan,
    prepared_plan: VulkanPreparedDispatchPlan,
    loaded_manifest: VulkanLoadedReusableKernelArtifactManifest,
    batch_kernels: Vec<VulkanResidentComponentBatchKernelArtifact>,
    parameter_buffers: Arc<VulkanPermanentParameterBuffers>,
}
