pub struct VulkanResidentInProcessPlacedModelPackage {
    pub package_id: String,
    pub input_device_id: String,
    pub output_device_id: String,
    pub dynamic_state_capacity_activations: usize,
    pub device_ids: Vec<String>,
    pub device_count: usize,
    pub hosted_pedal_count: usize,
    pub transducer_parameter_count: usize,
    pub transducer_parameter_bytes: usize,
    input_transducer_parameter_buffers: Arc<VulkanPermanentParameterBuffers>,
    output_transducer_parameter_buffers: Arc<VulkanPermanentParameterBuffers>,
    input_transducer_spirv_words: Vec<u32>,
    input_transducer_batch_spirv_words: Vec<u32>,
    embedding_norm_spirv_words: Vec<u32>,
    embedding_norm_batch_spirv_words: Vec<u32>,
    embedding_norm_batch_lane_tile_width: u32,
    tied_projection_spirv_words: Vec<u32>,
    tied_projection_batch_spirv_words: Vec<u32>,
    projection_batch_lane_tile_width: u32,
    sampler_kernels: Vec<VulkanResidentSamplerKernelArtifact>,
    input_transducer_spec: VulkanResidentInputEmbeddingTransducerSpec,
    output_transducer_spec: VulkanResidentOutputTransducerSpec,
    sampler_spec: VulkanResidentSamplerSpec,
    device_slices: Vec<Arc<VulkanResidentModelPackageDeviceSlice>>,
    speculative_decoders: Vec<VulkanResidentSpeculativeDecoderModelPackage>,
    distributed_execution_plan: VulkanDistributedExecutionPlan,
    distributed_activation_plan: VulkanDistributedActivationBufferPlan,
    distributed_parameter_allocation_plan: VulkanDistributedParameterAllocationPlan,
    distributed_parameter_exclusion_plan: VulkanDistributedParameterExclusionPlan,
    distributed_loaded_manifest: VulkanLoadedReusableKernelArtifactManifest,
    distributed_parameter_buffers: Arc<VulkanDistributedParameterBuffers>,
}
